server:
  port: 7002
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myapple-lipan-code/user_cloud_Configuration/
          username: myapple-lipan-code
          password: lipan15879542940
          search-paths: configserver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka