spring:
  application:
    name: UserWeb02
    #配置thymeleaf 缓存不要开启
  thymeleaf:
    cache: false
server:
  port: 9002

#配置eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
